# # -*- coding: utf-8 -*-
# """DeepFM.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/14Q-cvOmtOtKox3Jlob0IO05i2015nECK
# """

import os, urllib.request, zipfile
import numpy as np
import torch
from torch.utils.data import Dataset
from collections import defaultdict

# """Chuẩn bị công cụ
# - đọc file
# - xử lý dữ liệu
# - tạo dataset cho PyTorch
# """

#  Download dataset
# url = "http://d2l-data.s3-accelerate.amazonaws.com/ctr.zip"
# if not os.path.exists("ctr"):
#     urllib.request.urlretrieve(url, "ctr.zip")
#     with zipfile.ZipFile("ctr.zip", 'r') as zip_ref:
#         zip_ref.extractall()

# """Nếu chưa có dữ liệu → tải về → giải nén

# Kết quả:
# ctr/train.csv
# ctr/test.csv
# """

#  Dataset
class CTRDataset(Dataset):
    def __init__(self, path, feat_mapper=None, defaults=None, min_threshold=4, num_feat=34):
        self.NUM_FEATS = num_feat
        self.data = []
        feat_cnts = defaultdict(lambda: defaultdict(int))
        self.feat_mapper = feat_mapper
        self.defaults = defaults

        with open(path) as f:
            for line in f:
                values = line.strip().split('\t')
                if len(values) != self.NUM_FEATS + 1:
                    continue

                y = float(values[0])
                x = values[1:]

                for i, v in enumerate(x):
                    feat_cnts[i][v] += 1

                self.data.append((x, y))

        if self.feat_mapper is None:
            feat_mapper = {
                i: {feat for feat, c in cnt.items() if c >= min_threshold}
                for i, cnt in feat_cnts.items()
            }
            self.feat_mapper = {
                i: {v: idx for idx, v in enumerate(vals)}
                for i, vals in feat_mapper.items()
            }
            self.defaults = {i: len(vals) for i, vals in feat_mapper.items()}

        self.field_dims = np.array([len(self.feat_mapper[i]) + 1 for i in range(self.NUM_FEATS)])
        self.offsets = np.array([0] + list(np.cumsum(self.field_dims)[:-1]))

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        x, y = self.data[idx]

        feat = np.array([
            self.feat_mapper[i].get(v, self.defaults[i])
            for i, v in enumerate(x)
        ])

        feat = feat + self.offsets

        return torch.tensor(feat, dtype=torch.long), torch.tensor(y, dtype=torch.float32)

# """dùng để xử lý dữ liệu cho mô hình học máy, đặc biệt trong bài toán dự đoán Click-Through Rate (CTR) - tức là dự đoán người dùng có click vào quảng cáo hay không"""

#  Load train/test
# train_data = CTRDataset("ctr/train.csv")
# test_data = CTRDataset(
#     "ctr/test.csv",
#     feat_mapper=train_data.feat_mapper,
#     defaults=train_data.defaults
# )
train_data = CTRDataset("data/raw/ctr/train.csv")
test_data = CTRDataset("data/raw/ctr/test.csv",
                       feat_mapper=train_data.feat_mapper,
                       defaults=train_data.defaults)


print("Train size:", len(train_data))
print("Test size:", len(test_data))

# """train_data = CTRDataset("ctr/train.csv"):

# Tạo một đối tượng CTRDataset từ file ctr/train.csv. Đây là dữ liệu dùng để huấn luyện mô hình.
# Trong quá trình khởi tạo này, lớp CTRDataset sẽ tự động phân tích train.csv để xây dựng feat_mapper (ánh xạ các giá trị đặc trưng thành số nguyên) và defaults (giá trị mặc định cho các đặc trưng không đủ tần suất xuất hiện).
# test_data = CTRDataset("ctr/test.csv", feat_mapper=train_data.feat_mapper, defaults=train_data.defaults):

# Tạo một đối tượng CTRDataset khác từ file ctr/test.csv. Đây là dữ liệu dùng để đánh giá mô hình.
# Quan trọng: Thay vì để test_data tự động xây dựng feat_mapper và defaults riêng, nó nhận feat_mapper và defaults đã được tạo ra từ train_data. Điều này đảm bảo rằng các đặc trưng trong tập test được ánh xạ và xử lý thống nhất với tập train, tránh rò rỉ thông tin từ tập test và đảm bảo mô hình hoạt động đúng cách trên dữ liệu mới.
# """

import torch
import torch.nn as nn
from torch.utils.data import DataLoader

#  Model
class DeepFM(nn.Module):
    def __init__(self, field_dims, embed_dim=10, mlp_dims=[30,20,10], dropout=0.1):
        super().__init__()
        self.num_fields = len(field_dims)
        num_inputs = int(sum(field_dims))

        self.embedding = nn.Embedding(num_inputs, embed_dim) # 1. Tạo ma trận E (embedding matrix) 2. Khởi tạo NGẪU NHIÊN (random)
        self.fc = nn.Embedding(num_inputs, 1)

        input_dim = self.num_fields * embed_dim
        layers = []
        for dim in mlp_dims:
            layers += [nn.Linear(input_dim, dim), nn.ReLU(), nn.Dropout(dropout)]
            input_dim = dim
        layers.append(nn.Linear(input_dim, 1))
        self.mlp = nn.Sequential(*layers)

    def forward(self, x):
        #FM
        embed_x = self.embedding(x) # e = onehot x E

        square_of_sum = torch.sum(embed_x, dim=1) ** 2
        sum_of_square = torch.sum(embed_x ** 2, dim=1)
        fm = 0.5 * torch.sum(square_of_sum - sum_of_square, dim=1, keepdim=True)

        linear = self.fc(x).sum(dim=1)

        #Deep
        deep = self.mlp(embed_x.view(embed_x.size(0), -1))

        return torch.sigmoid(linear + fm + deep)

# """Input (34 feature)
# ↓
# Embedding
# ↓
# Tách 3 nhánh:
#  1. Linear (nhớ đơn giản)
#  2. FM (bắt cặp feature)
#  3. Deep (MLP học phức tạp)
# ↓
# Cộng lại → sigmoid → xác suất click


# """

# # chuyển đoạn natf qa train.py
# #  lay DataLoader
# train_loader = DataLoader(train_data, batch_size=2048, shuffle=True)
# test_loader = DataLoader(test_data, batch_size=2048)
# # - lấy dữ liệu từ train_data
# # - chia thành từng batch 2048 dòng
# # - shuffle (trộn ngẫu nhiên)

# #  Init
# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# # Nếu có GPU → dùng GPU
# # Không có → dùng CPU
# # train nhanh hơn nếu có GPU

# model = DeepFM(train_data.field_dims).to(device)
# # DeepFM(field_dims)
# # → khởi tạo toàn bộ:
# # - embedding (E random)
# # - FM
# # - MLP (deep)
# # .to(device)
# # → đưa model lên GPU/CPU

# criterion = nn.BCELoss()
# # Binary Cross Entropy dùng cho bài toán 0 / 1 (click / không click)


# optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
# # câp nhât trong số
# # optimizer sẽ update:
# # - embedding (E)
# # - fc (linear part)
# # - mlp (deep part)

# #  Train + Eval
# for epoch in range(10): #Cho model học qua toàn bộ dữ liệu 10 lần

#     model.train() #- Dropout hoạt động  - BatchNorm (nếu có) update
#     total_loss = 0

#     for X, y in train_loader: #X: (batch, 34) y: (batch,)
#         X, y = X.to(device), y.to(device).unsqueeze(1) #thành X: (batch, 34) y: (batch, 1)

#         preds = model(X) #Embedding → FM + Deep + Linear → sigmoid => opupt (batch, 1) ~ xác suất click
#         loss = criterion(preds, y) # so sanh preds vs y (0 hoặc 1)

#         optimizer.zero_grad()
#         loss.backward()
#         optimizer.step()
#         # zero_grad → reset gradient
#         # backward → tính gradient
#         # step → cập nhật weight
#         # lúc này Embedding + FM + Deep đều được học

#         total_loss += loss.item() #để in ra cuối epoch

#     # eval
#     model.eval() #tắt Dropout
#     correct, total = 0, 0

#     with torch.no_grad(): #nhanh hơn + tiết kiệm RAM
#         for X, y in test_loader:
#             X, y = X.to(device), y.to(device)
#             preds = (model(X) > 0.5).float().squeeze() # > 0.5 → 1 (click) ≤ 0.5 → 0
#             correct += (preds == y).sum().item()
#             total += y.size(0)

#     print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}, Acc: {correct/total:.4f}")
#     torch.save(model.state_dict(), "models/deepfm_model.pth")
